### ISSUE TITLE
Error when initializing with no slides added to the DOM

### ISSUE THREAD

**Issue by taysloane** [taylorrees/peek.js#1]
After including `peek.min.js` and `peek.css`, but no slides, there's an error. It's not really an issue, given you can't use it without slides anyway, but something to consider.

`TypeError: null is not an object (evaluating 'document.querySelector(".peek .slides").children')`

**Comment by taysloane** [comment]
Actually, this is definitely a problem for Single Page Apps. I'm using Angular, putting the slides in my partials. So when Peek is loaded, the slides aren't in the DOM yet, and the error's thrown.

One option would be to load slides when `Peek.init()` is called rather than when the library is loaded. So instead of setting up Slides as a `var`, just convert it into a function that's called from `Peek.init()`.

That being said, making that change causes an infinite Digest loop in Angular, so that's clearly not the best plan! Essentially I want to load different slide sets on each page, and the slides won't be in the DOM when the library is first loaded.

**Comment by taylorrees** [comment]
Hi Jake, I've had a look at the `TypeError` you've described above and I am able to reproduce it. From my understanding the problem arises when the `<div class="slides"></div>` is not within the `<div class="peek"></div>` element and the script is then called?

Currently, it is required that the following element hierarchy is obeyed, such that the `peek` element must always contain a `slides` element. 

``` html
<div class="peek">
    <div class="slides">
        <section>Slide 1</section>
        <section>Slide 2</section>
    </div>
</div>
```

Where the `<div class="slides"></div>` may contain 0 or more `<section></section>` elements. This means that you can initialise Peek with no slides. You should then be able to add slides and reinitialise the walkthrough. Perhaps you could store individual slides in your Angular partials and add these to the walkthrough periodically.

I hope this fixes your problem and if not, just let me know.

**Comment by taysloane** [comment]
Well I guess there's two problems (both solvable, but could be solved better):
1. If you load `peek.js` in the `<head>` the slides don't exist yet, so it throws an error.
2. If you change the slides in the DOM, they don't get refreshed in the `Slides` object, because that's only loaded the first time `peek.js` is loaded

You can solve 1. by including the .js file before the closing `</body>` instead, but 2. is more of an issue for SPAs, where changing routes doesn't cause `peek.js` to get loaded again.

**Comment by taylorrees** [comment]
Hi Jake, 

First of all can I begin by apologising for the delay in implementing a solution to the issue you raised. It's been a crazy few weeks but I hope that I've made some real progress on the issue.

The codebase has been re-written and split into modules. I hope this will improve the readability of the code and also make fixes easier in the future. Part of my reason for doing this was to allow multiple instances of the Peek object to be created, thus meaning each can have its own methods. I hope this will make Peek a better suited to a life within an SPA.

Hope you get the chance to take a look.

Thanks,

Taylor

**Comment by taysloane** [comment]
I've only skimmed through, but it looks pretty great so far. Nice rewrite! I'll take a proper look in a couple days when I get a little more time 👍

**Comment by taylorrees** [comment]
Thank you 😄
